#!/usr/bin/env python3
"""Original bounded exact policies; no external data or dependencies."""
from functools import lru_cache
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[2]
triples = [sum(1<<v for v in (a,b,c)) for a in range(9) for b in range(a+1,9) for c in range(b+1,9) if a+b+c+3==15]
def won(mask): return any(mask&t==t for t in triples)
@lru_cache(None)
def euclid(a,b):
    if not a or not b: return 0
    a,b=sorted((a,b))
    return int(any(not euclid(a,b-k*a) for k in range(1,b//a+1)))
w=[[0]*41 for _ in range(41)]
for total in range(1,81):
    for a in range(41):
        b=total-a
        if not 0<=b<=40: continue
        w[a][b]=int(any(not w[a-k][b] for k in range(1,a+1)) or any(not w[a][b-k] for k in range(1,b+1)) or any(not w[a-k][b-k] for k in range(1,min(a,b)+1)))
@lru_cache(None)
def fifteen(mine,theirs):
    if won(mine): return 1
    if won(theirs): return -1
    free=511^(mine|theirs)
    if not free: return 0
    return max(-fifteen(theirs,mine|(1<<i)) for i in range(9) if free>>i&1)
values=[]
for code in range(3**9):
    n=code;mine=theirs=0
    for i in range(9):
        p=n%3;n//=3
        if p==1:mine|=1<<i
        if p==2:theirs|=1<<i
    values.append(fifteen(mine,theirs)+1)
def pack(values,bits):
    out=[]
    for i in range(0,len(values),8//bits):
        out.append(sum(v<<(bits*j) for j,v in enumerate(values[i:i+8//bits])))
    return out
arrays={'sq_wythoff_bits':pack([w[a][b] for a in range(41) for b in range(41)],1), 'sq_euclid_bits':pack([euclid(a,b) for a in range(100) for b in range(100)],1),'sq_fifteen_values':pack(values,2)}
out=['/* Generated by tools/generate/strategyquick_tables.py; original data. */','#ifndef STRATEGYQUICK_TABLES_H','#define STRATEGYQUICK_TABLES_H','#include <stdint.h>']
for name,data in arrays.items():
    out.append(f'static const uint8_t {name}[{len(data)}] = {{')
    out += [' '+','.join(str(v) for v in data[i:i+24])+',' for i in range(0,len(data),24)]
    out.append('};')
out.append('#endif')
(ROOT/'assets/strategyquick/tables.h').write_text('\n'.join(out)+'\n')
(ROOT/'assets/strategyquick/metadata.json').write_text(json.dumps({'rules_version':1,'generated_by':'strategyquick_tables.py','provenance':'original exact state analysis','domains':{'wythoff':[0,40],'euclid':[0,99],'make_fifteen_states':3**9},'table_bytes':{k:len(v) for k,v in arrays.items()}},indent=2)+'\n')
print(json.dumps({k:len(v) for k,v in arrays.items()}))
