#include "strategyquick.h"

const NgModule ng_strategyquick[10]={
 {21,"NIM","NIM",
 "Take stones from exactly one pile.\nThe last stone wins (normal play).\nArrows select pile; type amount, EXE.\nEasy: 3 piles up to 7; Normal: up to 15.\nHard: 4 piles up to 31.\nCPU Easy random, Normal 75% exact,\nHard uses the exact nim-sum policy.\nMASTER: verified four-pile tactical starts.\nPlay against CPU: YOU FIRST or CPU FIRST.\nMASTER keeps the same exact Hard CPU.\nIts starts allow YOU a forced win.\nUNDO restores your complete CPU round.\nUNDO marks assisted practice.",
 NGF_CPU|NGF_UNDO,NULL,"TAKE",2,sq_strategy_mode,sq_strategy_init,sq_strategy_action,NULL,sq_strategy_valid,sq_strategy_render},
 {22,"WYTHOFF","WYTHOFF",
 "Take from one pile, or take the same\npositive amount from both piles.\nEmpty both piles to win.\nArrows select A / B / BOTH.\nType amount and press EXE.\nPile ranges: Easy 1..10, Normal 1..24,\nHard 1..40. Exact bounded DP on Hard.\nMASTER: verified long tactical starts.\nEasy random; Normal 75% exact moves.\nPlay against CPU: YOU FIRST or CPU FIRST.\nMASTER keeps the same exact Hard CPU.\nIts starts allow YOU a forced win.\nUNDO restores the complete CPU round.",
 NGF_CPU|NGF_UNDO,NULL,"TAKE",2,sq_strategy_mode,sq_strategy_init,sq_strategy_action,NULL,sq_strategy_valid,sq_strategy_render},
 {23,"EUCLID","EUCLID",
 "Subtract k times SMALL from LARGE.\nk is a positive integer; no negatives.\nMaking zero wins. Values are re-sorted.\nType k in the shown range; EXE to play.\nEasy values 1..12; Normal 1..40;\nHard 1..99. All rules stay the same.\nHard uses exact memoized state analysis.\nMASTER: coprime multi-step tactical starts.\nEasy random; Normal 75% exact moves.\nPlay against CPU: YOU FIRST or CPU FIRST.\nMASTER keeps the same exact Hard CPU.\nIts starts allow YOU a forced win.\nUNDO restores the complete CPU round.",
 NGF_CPU|NGF_UNDO,NULL,"PLAY",2,sq_strategy_mode,sq_strategy_init,sq_strategy_action,NULL,sq_strategy_valid,sq_strategy_render},
 {24,"MAKE FIFTEEN","MAKE FIFTEEN",
 "Take unused cards from 1 to 9.\nAny three of YOUR cards summing to 15\nwin, even when you hold more than three.\nAll cards used without a winner: draw.\nArrows + EXE, or a digit to take a card.\nBlue marks YOU; red marks CPU.\nEasy random; Normal 75% exact moves.\nHard uses the full exact minimax table.\nMASTER: verified midgame tactical starts.\nPlay against CPU: YOU FIRST or CPU FIRST.\nMASTER keeps the same exact Hard CPU.\nIts starts allow YOU a forced win.\nUNDO restores the complete CPU round.",
 NGF_CPU|NGF_UNDO,NULL,"TAKE",2,sq_strategy_mode,sq_strategy_init,sq_strategy_action,NULL,sq_strategy_valid,sq_strategy_render},
 {25,"RACE TO TARGET","RACE TARGET",
 "Take turns adding to the running total.\nReach the target EXACTLY to win.\nAn addition beyond the target is illegal.\nType the addition, then EXE.\nEasy: target 21; add 1, 2, or 3.\nNormal: target 31; add 1, 2, or 3.\nHard: target 23; add 1, 2, 3, or 4.\nHard uses exact addition-game analysis.\nMASTER: varied tactical target/add limits.\nEasy random; Normal 75% exact moves.\nPlay against CPU: YOU FIRST or CPU FIRST.\nMASTER keeps the same exact Hard CPU.\nIts starts allow YOU a forced win.",
 NGF_CPU|NGF_UNDO,NULL,"ADD",2,sq_strategy_mode,sq_strategy_init,sq_strategy_action,NULL,sq_strategy_valid,sq_strategy_render},
 {26,"2048","2048",
 "Arrows slide all tiles. Equal tiles merge\nonce each move; merged value adds score.\nA changed move spawns 2 (90%) or 4 (10%).\nBlocked moves consume no random numbers.\nCLASSIC: reach 2048 and continue playing.\nTARGET goals E/N/H/M:512/1024/2048/8192.\nTARGET ends when its goal tile is reached.\nCLASSIC uses a fixed level.\nNo legal moves means game over.\nUNDO restores tiles, score, and RNG;\nit marks the run as assisted practice.\nTiles cap at 2^30 and cannot merge beyond.\nScore saturates at 4294967295 safely.\nLarge tiles use exact 2^n notation.",
 NGF_UNDO,NULL,NULL,2,sq_2048_mode,sq_quick_init,sq_quick_action,NULL,sq_quick_valid,sq_quick_render},
 {27,"SLIDING PUZZLE","SLIDING",
 "Put 1..8 or 1..15 in reading order,\nwith the blank in the bottom-right.\nArrows move the BLANK in that direction.\nChoose a 3x3 or 4x4 board in MODE.\nNew E/N/H starts have exact distances:\nEASY 8..14, NORMAL 15..20, HARD 21..26.\nEach size/level has 128 certified starts.\nMASTER 3x3: exact distance 31 (2 starts).\nMASTER 4x4: at least 48 moves (30 starts).\n4x4 MASTER distances are lower bounds.\nOlder runs keep their original shuffles.\nEvery start is solvable; UNDO reverses\nyour moves. Size stays in MODE.",
 NGF_UNDO,NULL,NULL,2,sq_sliding_mode,sq_quick_init,sq_quick_action,NULL,sq_quick_valid,sq_quick_render},
 {28,"LIGHTS OUT","LIGHTS OUT",
 "Turn every light off. Arrows select.\nEXE or 5 toggles the selected light and\nits orthogonal neighbours (no wrapping).\nModes: 4x4 or 5x5. Both start solvable.\nNew 4x4 E/N/H minima: 2/4/5 presses.\nOlder 4x4 starts keep their shuffle rules.\n5x5 E/N/H use 4/8/18 generating presses;\nthese are not minimum solution counts.\nMASTER: certified minimum-press starts.\n4x4 needs 6; 5x5 needs 12..14 presses.\nEvery valid solution is accepted.\nHINT uses Gaussian elimination over GF(2).\nPress the highlighted cell next.\nThe hint does not promise fewest moves.\nHINT/UNDO mark assisted practice.",
 NGF_UNDO|NGF_HINT,NULL,"PRESS",2,sq_lights_mode,sq_quick_init,sq_quick_action,NULL,sq_quick_valid,sq_quick_render},
 {29,"ARITHMETIC RUSH","ARITH RUSH",
 "Answer as many problems as you can.\nType an integer; EXE submits.\nAfter feedback, release and EXE for next.\nEasy: small nonnegative + and -.\nNormal: wider + - x /, negatives allowed.\nHard: bigger numbers and two steps.\nAll division problems have integer answers.\nScore: 10 + twice the current combo.\n60-second mode counts active play only.\nF4 pauses. Practice has no timer;\npress = to finish an untimed practice run.",
 NGF_TIMED,"PAUSE","ANSWER",2,sq_rush_mode,sq_quick_init,sq_quick_action,sq_quick_tick,sq_quick_valid,sq_quick_render},
 {30,"NUMBER MEMORY","NUMBER MEMORY",
 "Remember the digit sequence in order.\nAfter it is hidden, type all the digits.\nLeading zeros matter. EXE submits.\nCorrect: EXE starts the next round.\nWrong: compare your entry to the sequence.\nComplete 20 rounds to finish the run.\nEasy starts at 3 digits; Normal 4; Hard 5.\nEvery two rounds the sequence grows.\nExposure grows with length; Hard is faster.\nF4 pauses; resume preserves exposure left.\nDisplayed, hidden, input, and result phases\nhave release barriers against held keys.",
 NGF_TIMED,"PAUSE","SUBMIT",1,NULL,sq_quick_init,sq_quick_action,sq_quick_tick,sq_quick_valid,sq_quick_render}
};
