#!/usr/bin/env python3
"""Losslessly pack the fixed beta.6 Make Target bank for native random access.

The JSON and its original C header are host-only reference material. This
script never generates or regrades puzzles. Run --write after an intentional
content change, and --check in the normal verification pipeline.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools' / 'generate'))
from guesscalc_beta6_target import c_header  # noqa: E402

SOURCE = ROOT / 'assets/guesscalc_target_beta6.json'
REFERENCE = ROOT / 'assets/guesscalc_target_beta6.h'
PACKED = ROOT / 'assets/guesscalc_target_beta6_packed.h'
MANIFEST = ROOT / 'assets/guesscalc_target_beta6_manifest.jsonl'
TARGETS = (10, 24, 50, 100, 200)
OPS = '+-*/'
TOKEN = {'+': 6, '-': 7, '*': 8, '/': 9, '(': 10, ')': 11}
CARD_BYTES = (5, 5, 7, 8)
ANSWER_BYTES = (7, 7, 9, 11)
STRIDES = tuple(c + 1 + a for c, a in zip(CARD_BYTES, ANSWER_BYTES))
TOTAL = sum(1000 * stride for stride in STRIDES)


def tokens(answer, cards):
    parts = re.findall(r'\d+|[()+*/-]', answer)
    if ''.join(parts) != answer:
        raise ValueError('unsupported answer character')
    used = [False] * len(cards)
    result = []
    for part in parts:
        if part.isdecimal():
            value = int(part)
            slot = next((i for i, card in enumerate(cards)
                         if card == value and not used[i]), None)
            if slot is None or str(value) != part:
                raise ValueError('answer literal does not match one unused card')
            used[slot] = True
            result.append(slot)
        else:
            result.append(TOKEN[part])
    if not all(used):
        raise ValueError('answer did not use every card occurrence')
    return result


def cards10(cards, count):
    out = bytearray((count * 10 + 7) // 8)
    for i, value in enumerate(cards):
        if not 1 <= value <= 999:
            raise ValueError('card out of range')
        for bit in range(10):
            out[(i * 10 + bit) // 8] |= ((value >> bit) & 1) << ((i * 10 + bit) % 8)
    return out


def manifest_row(row, ordinal):
    difficulty, within = divmod(ordinal, 1000)
    count = 4 if difficulty < 2 else difficulty + 3
    target = TARGETS[within // 200]
    cards = row['cards']
    if (row['puzzle_id'] != 16240 + ordinal or row['difficulty'] != difficulty
            or row['target'] != target or len(cards) != count):
        raise ValueError('unstable ID, ordering, target or card count')
    a, b, op = row['hint']
    if not (isinstance(a, int) and isinstance(b, int) and 0 <= a < count
            and 0 <= b < count and a != b and op in OPS):
        raise ValueError('invalid hint')
    answer = row['answer']
    if len(answer) >= 40 or not tokens(answer, cards):
        raise ValueError('invalid answer')
    return dict(puzzle_id=row['puzzle_id'], difficulty=difficulty, target=target,
                card_count=count, cards=cards + [0] * (6 - count),
                hint_a=a, hint_b=b, hint_op=op,
                hint_text=f'One first step: {cards[a]} {op} {cards[b]}.',
                answer=answer)


def pack_row(row, ordinal):
    difficulty = ordinal // 1000
    cards = row['cards']
    count = len(cards)
    out = cards10(cards, count)
    if len(out) != CARD_BYTES[difficulty]:
        raise AssertionError('card width changed')
    a, b, op = row['hint']
    out.append(a | (b << 3) | (OPS.index(op) << 6))
    stream = tokens(row['answer'], cards)
    if len(stream) > ANSWER_BYTES[difficulty] * 2:
        raise ValueError('answer exceeds fixed random-access record')
    # A final high nibble 0xf is a terminator only for an odd token count.
    if len(stream) % 2:
        stream.append(15)
    if len(stream) != ANSWER_BYTES[difficulty] * 2:
        raise ValueError('unexpected token count; update the format explicitly')
    for i in range(0, len(stream), 2):
        out.append(stream[i] | (stream[i + 1] << 4))
    if len(out) != STRIDES[difficulty]:
        raise AssertionError('record width changed')
    return out


def render_header(blob, digest):
    lines = ['/* Generated by tools/pack_make_target.py; Make Target only. */',
             '#ifndef GUESSCALC_TARGET_BETA6_PACKED_H',
             '#define GUESSCALC_TARGET_BETA6_PACKED_H',
             '#define GC_TARGET_BETA6_PACK_FORMAT_VERSION 1u',
             f'#define GC_TARGET_BETA6_LOGICAL_SHA256 "{digest}"',
             f'static const uint8_t gc_target_beta6_packed[{TOTAL}] = {{']
    for i in range(0, len(blob), 16):
        lines.append(' ' + ','.join(f'0x{byte:02x}' for byte in blob[i:i + 16]) + ',')
    lines += ['};', '#endif', '']
    return '\n'.join(lines)


def produce():
    data = json.loads(SOURCE.read_text())
    if data['revision'] != 6 or data['targets'] != list(TARGETS) or len(data['records']) != 4000:
        raise ValueError('unexpected source content revision')
    if REFERENCE.read_text() != c_header(data):
        raise ValueError('original C reference disagrees with JSON')
    rows = data['records']
    manifest = ''.join(json.dumps(manifest_row(row, i), sort_keys=True,
                                  separators=(',', ':')) + '\n'
                       for i, row in enumerate(rows))
    digest = hashlib.sha256(manifest.encode('ascii')).hexdigest()
    blob = b''.join(pack_row(row, i) for i, row in enumerate(rows))
    if len(blob) != TOTAL:
        raise AssertionError('packed size changed')
    return render_header(blob, digest), manifest, digest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--check', action='store_true')
    args = parser.parse_args()
    header, manifest, digest = produce()
    if args.write:
        PACKED.write_text(header)
        MANIFEST.write_text(manifest)
    elif PACKED.read_text() != header or MANIFEST.read_text() != manifest:
        raise ValueError('stale packed header or logical manifest')
    rows = json.loads(SOURCE.read_text())['records']
    # Alternative A keeps all 16 literal characters in nibbles and a nibble
    # length delta per answer. Fixed per-level strides avoid an offset table.
    plain_text = 0
    for difficulty in range(4):
        lengths = [len(row['answer']) for row in rows[difficulty*1000:(difficulty+1)*1000]]
        if max(lengths)-min(lengths)>15:
            raise ValueError('literal nibble length needs a wider prefix')
        plain_text += 1000*((max(lengths)+2)//2)
    plain_candidate = 25000+4000+plain_text
    print(f'PASS Make Target 4000 logical records SHA256 {digest}; '
          f'card-reference pack {TOTAL} B; host-only literal-nibble candidate {plain_candidate} B')


if __name__ == '__main__':
    main()
